//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventUsers = new HashSet<EventUser>();
        }
    
        public long Id { get; set; }
        public string Location { get; set; }
        public string EventId { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsAllDay { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string OrganizerMail { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> IsReccurnce { get; set; }
        public string FormattedLocation { get; set; }
    
        public virtual ICollection<EventUser> EventUsers { get; set; }
    }
}
