//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempEvent
    {
        public long Id { get; set; }
        public string Location { get; set; }
        public string Title { get; set; }
        public string ReturnMail { get; set; }
        public string ReturnName { get; set; }
        public string RequestId { get; set; }
        public string Desc { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsAllDay { get; set; }
    
        public virtual User User { get; set; }
    }
}
